# Generated by Django 5.2.5 on 2025-08-24 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='scholarship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarshippost'),
        ),
    ]
